server:
  port: 8080
spring:
  application:
    name: "MovieApp"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
adapter:
  restconsumer:
    url: "https://api.themoviedb.org/3"
    apikey: "b367c4d7f17840d073f27e0d2ed45f0d"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
